# Generated by Django 6.0.5 on 2026-05-13 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('S1', 'Stage 1'), ('S2', 'Stage 2'), ('S3', 'Stage 3')], editable=False, max_length=2)),
                ('data', models.JSONField(default=dict)),
                ('created_on', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DiagnosticJourney',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PROG', 'In Progress'), ('CVAL', 'Clinically Validated'), ('COMP', 'Complete')], max_length=4)),
                ('created_on', models.DateField(auto_now_add=True)),
                ('updated_on', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AssessmentResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateField(auto_now_add=True)),
                ('score', models.DecimalField(decimal_places=4, editable=False, max_digits=5)),
                ('risk', models.TextField(choices=[('HIGH', 'High'), ('MED', 'Medium'), ('LOW', 'Low')], editable=False, max_length=4)),
                ('recommendation', models.TextField()),
                ('explanation', models.JSONField(default=list)),
                ('assessment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='journeys.assessmentstage')),
            ],
        ),
    ]
