# Generated by Django 6.0.5 on 2026-05-19 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosticJourney',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(editable=False)),
                ('status', models.CharField(choices=[('PROG', 'In Progress'), ('COMP', 'Completed')], default='PROG', max_length=4)),
                ('created_on', models.DateField(auto_now_add=True)),
                ('updated_on', models.DateField(auto_now=True)),
                ('clinic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journeys', to='clinics.clinic')),
            ],
        ),
    ]
