# Generated by Django 6.0.5 on 2026-05-13 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('journeys', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosticjourney',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnostic_journey', to='users.patientprofile'),
        ),
        migrations.AddField(
            model_name='assessmentstage',
            name='journey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment', to='journeys.diagnosticjourney'),
        ),
        migrations.AddConstraint(
            model_name='assessmentstage',
            constraint=models.UniqueConstraint(fields=('journey', 'stage'), name='unique_stage_per_journey'),
        ),
    ]
