# Generated by Django 6.0.5 on 2026-05-15 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journeys', '0002_initial'),
        ('users', '0002_alter_patientprofile_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('S1', 'Stage 1'), ('S2', 'Stage 2'), ('S3', 'Stage 3')], editable=False, max_length=2)),
                ('data', models.JSONField(default=dict)),
                ('created_on', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClinicalNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateField(auto_now_add=True)),
                ('updated_on', models.DateField(auto_now=True)),
                ('content', models.TextField()),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='assessmentstage',
            name='unique_stage_per_journey',
        ),
        migrations.AddField(
            model_name='diagnosticjourney',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journeys', to='users.doctorprofile'),
        ),
        migrations.AddField(
            model_name='diagnosticjourney',
            name='number',
            field=models.PositiveSmallIntegerField(default=1, editable=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='assessmentresult',
            name='recommendation',
            field=models.TextField(choices=[('END', 'Endocrinology'), ('GYN', 'Gynecology'), ('GEN', 'General Practitioner')], max_length=3),
        ),
        migrations.AlterField(
            model_name='diagnosticjourney',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journeys', to='users.patientprofile'),
        ),
        migrations.AlterField(
            model_name='diagnosticjourney',
            name='status',
            field=models.CharField(choices=[('PROG', 'In Progress'), ('COMP', 'Completed')], max_length=4),
        ),
        migrations.AddField(
            model_name='assessment',
            name='journey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='journeys.diagnosticjourney'),
        ),
        migrations.AlterField(
            model_name='assessmentresult',
            name='assessment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='journeys.assessment'),
        ),
        migrations.AddField(
            model_name='clinicalnote',
            name='assessment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_notes', to='journeys.assessment'),
        ),
        migrations.RemoveField(
            model_name='assessmentstage',
            name='journey',
        ),
        migrations.AddConstraint(
            model_name='assessment',
            constraint=models.UniqueConstraint(fields=('journey', 'stage'), name='unique_stage_per_journey'),
        ),
        migrations.DeleteModel(
            name='AssessmentStage',
        ),
    ]
