# Generated by Django 6.0.5 on 2026-05-16 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
        ('journeys', '0003_assessment_clinicalnote_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='assessment',
            name='unique_stage_per_journey',
        ),
        migrations.RemoveField(
            model_name='assessmentresult',
            name='assessment',
        ),
        migrations.RemoveField(
            model_name='clinicalnote',
            name='assessment',
        ),
        migrations.AlterField(
            model_name='diagnosticjourney',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journeys', to='doctors.doctorprofile'),
        ),
    ]
