# Generated by Django 6.0.5 on 2026-05-16 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journeys', '0004_remove_assessment_unique_stage_per_journey_and_more'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosticjourney',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journeys', to='patients.patientprofile'),
        ),
        migrations.AlterField(
            model_name='diagnosticjourney',
            name='status',
            field=models.CharField(choices=[('PROG', 'In Progress'), ('COMP', 'Completed')], default='PROG', max_length=4),
        ),
        migrations.RemoveField(
            model_name='assessment',
            name='journey',
        ),
        migrations.DeleteModel(
            name='AssessmentResult',
        ),
        migrations.DeleteModel(
            name='ClinicalNote',
        ),
        migrations.DeleteModel(
            name='Assessment',
        ),
    ]
