# Generated by Django 6.0.5 on 2026-05-18 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0001_initial'),
        ('journeys', '0005_alter_diagnosticjourney_patient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosticjourney',
            name='clinic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journeys', to='clinics.clinic'),
        ),
    ]
