# Generated by Django 6.0.5 on 2026-05-16 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('journeys', '0003_assessment_clinicalnote_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('S1', 'Stage 1'), ('S2', 'Stage 2'), ('S3', 'Stage 3')], editable=False, max_length=2)),
                ('data', models.JSONField(default=dict)),
                ('created_on', models.DateField(auto_now_add=True)),
                ('journey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='journeys.diagnosticjourney')),
            ],
        ),
        migrations.CreateModel(
            name='AssessmentResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateField(auto_now_add=True)),
                ('risk', models.CharField(choices=[('HIGH', 'High'), ('MED', 'Medium'), ('LOW', 'Low')], editable=False, max_length=4)),
                ('score', models.DecimalField(decimal_places=4, editable=False, max_digits=5)),
                ('top_factors', models.JSONField(default=list)),
                ('specialist', models.CharField(choices=[('END', 'Endocrinologist'), ('GYN', 'Gynecologist'), ('GEN', 'General Practitioner')], max_length=3)),
                ('clinical_focus', models.TextField()),
                ('next_step', models.TextField()),
                ('recommendation', models.TextField()),
                ('assessment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='assessments.assessment')),
            ],
        ),
        migrations.CreateModel(
            name='ClinicalNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateField(auto_now_add=True)),
                ('updated_on', models.DateField(auto_now=True)),
                ('content', models.TextField()),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_notes', to='assessments.assessment')),
            ],
        ),
        migrations.AddConstraint(
            model_name='assessment',
            constraint=models.UniqueConstraint(fields=('journey', 'stage'), name='unique_stage_per_journey'),
        ),
    ]
