# Generated by Django 6.0.5 on 2026-05-19 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('S1', 'Stage 1'), ('S2', 'Stage 2'), ('S3', 'Stage 3')], editable=False, max_length=2)),
                ('data', models.JSONField(default=dict)),
                ('created_on', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AssessmentResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateField(auto_now_add=True)),
                ('risk', models.CharField(choices=[('HIGH', 'High'), ('MOD', 'Moderate'), ('LOW', 'Low')], editable=False, max_length=4)),
                ('score', models.DecimalField(decimal_places=4, editable=False, max_digits=5)),
                ('top_factors', models.JSONField(default=list)),
                ('specialist', models.CharField(choices=[('END', 'Endocrinologist'), ('GYN', 'Gynecologist'), ('GEN', 'General Practitioner')], max_length=3)),
                ('clinical_focus', models.TextField()),
                ('next_step', models.TextField()),
                ('recommendation', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ClinicalNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateField(auto_now_add=True)),
                ('updated_on', models.DateField(auto_now=True)),
                ('content', models.TextField()),
            ],
        ),
    ]
