# Generated by Django 6.0.5 on 2026-05-18 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessmentresult',
            name='risk',
            field=models.CharField(choices=[('HIGH', 'High'), ('MOD', 'Moderate'), ('LOW', 'Low')], editable=False, max_length=4),
        ),
    ]
