# Generated by Django 6.0.5 on 2026-05-19 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assessments', '0001_initial'),
        ('journeys', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='journey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='journeys.diagnosticjourney'),
        ),
        migrations.AddField(
            model_name='assessmentresult',
            name='assessment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='assessments.assessment'),
        ),
        migrations.AddField(
            model_name='clinicalnote',
            name='assessment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_notes', to='assessments.assessment'),
        ),
        migrations.AddConstraint(
            model_name='assessment',
            constraint=models.UniqueConstraint(fields=('journey', 'stage'), name='unique_stage_per_journey'),
        ),
    ]
