# Generated by Django 6.0.5 on 2026-05-19 11:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='doctor_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('specialty', models.CharField(choices=[('END', 'Endocrinologist'), ('GYN', 'Gynecologist'), ('GEN', 'General Practitioner')], max_length=3)),
                ('hospital', models.CharField(max_length=128)),
            ],
        ),
    ]
