# Generated by Django 6.0.5 on 2026-05-16 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journeys', '0005_alter_diagnosticjourney_patient_and_more'),
        ('users', '0002_alter_patientprofile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='DoctorProfile',
        ),
        migrations.DeleteModel(
            name='PatientProfile',
        ),
    ]
