# Generated by Django 6.0.5 on 2026-05-19 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_patientprofile_user_delete_doctorprofile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('DR', 'Doctor'), ('PT', 'Patient'), ('CL', 'Clinician')], max_length=2),
        ),
    ]
